  File "/home/ian/projects/mol_diffusion/OMTRA/omtra_pipelines/plinder_clustering/generate_pairwise_cmds.py", line 33
      for f1, f2 in itertools.combinations_with_replacement(files, 2):
  ...
      print(f"Generated {args.bash_file} with {len(files)*(len(files)+1)//2} commands.")